//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.VehicleAnalyse.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.VehicleAnalyse.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1565_QuestionMarkBlue {
            get {
                object obj = ResourceManager.GetObject("_1565_QuestionMarkBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;CarLogo&gt;
        ///  &lt;item&gt;
        ///    &lt;id&gt;0&lt;/id&gt;
        ///    &lt;name&gt;奥迪&lt;/name&gt;
        ///    &lt;file&gt;奥迪.png&lt;/file&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;id&gt;1&lt;/id&gt;
        ///    &lt;name&gt;宝马&lt;/name&gt;
        ///    &lt;file&gt;宝马.png&lt;/file&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;id&gt;2&lt;/id&gt;
        ///    &lt;name&gt;现代&lt;/name&gt;
        ///    &lt;file&gt;现代.png&lt;/file&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;id&gt;3&lt;/id&gt;
        ///    &lt;name&gt;奔驰&lt;/name&gt;
        ///    &lt;file&gt;奔驰.png&lt;/file&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;id&gt;4&lt;/id&gt;
        ///    &lt;name&gt;本田&lt;/name&gt;
        ///    &lt;file&gt;本田.png&lt;/file&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;id&gt;5&lt;/id&gt;
        ///    &lt;name&gt;大众&lt;/name&gt;
        ///    &lt;file&gt;大众.png [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string carstyle {
            get {
                return ResourceManager.GetString("carstyle", resourceCulture);
            }
        }
    }
}
